# Generated by Django 3.0.5 on 2021-03-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_json',
            old_name='user_id',
            new_name='ID',
        ),
        migrations.AddField(
            model_name='user_json',
            name='docfile',
            field=models.FileField(default=1, upload_to='documents'),
            preserve_default=False,
        ),
    ]
